### ISSUE TITLE
pdf files are ignored

### ISSUE THREAD

**Issue by ddvlanck** [hazemhagrass/advanced-sitemap-generator#1]
When running this tool, URLs that lead to pdf documents (.pdf extension) are discovered, but they are not included in the sitemap.

**Comment by hazemhagrass** [comment]
@ddvlanck This is the default options for excluding files:
 excludeFileTypes:
    ['gif',
      'jpg',
      'jpeg',
      'png',
      'ico',
      'bmp',
      'ogg',
      'webp',
      'mp4',
      'webm',
      'mp3',
      'ttf',
      'woff',
      'woff2',
      'eot',
      'json',
      'rss',
      'atom',
      'gz',
      'zip',
      'rar',
      '7z',
      'css',
      'js',
      'gzip',
      'exe',
      'svg',
      'xml',
      '**pdf**',
      'ashx']

You may want to supply the same list to the options without the PDF file type.
