### ISSUE TITLE
on/off/start/stop methods return the instance for chaining

### ISSUE THREAD

**Issue by censys-git** [hazemhagrass/advanced-sitemap-generator#2]
**Do you want to request a *feature* or report a *bug*?** feature

**What is the current behavior?** returns void/undefined

**What is the expected behavior?** returns crawler/site generator instance

The on, off, start, and stop methods should return the instance so they can be chained.

example:
```javascript
(sitemapGenerator(url, options))
  .on('done', function() { ... })
  .on('error', function() { ... })
  .start();
```

**Comment by hazemhagrass** [comment]
no they should not do that because they are events. The generator should be defined as the following example:
```
const SitemapGenerator = require('advanced-sitemap-generator');

// create generator
const generator = SitemapGenerator('http://example.com', {
  stripQuerystring: false,
  ignoreHreflang: true
});

// register event listeners
generator.on('done', () => {
  // You have access to the generator object here
});

// start the crawler
generator.start();
```

**Comment by censys-git** [comment]
Sorry, I wasn't clear on my request. I'm not looking to access the generator instance inside the event callback. I'm asking that the actual event "method" (on, off), return the instance so you can chain them. Using your example:

```
// create generator
const generator = SitemapGenerator(...);

// register event listeners
generator.on('done', () => { /* You have access to the generator object here */});

// start the crawler
generator.start();
```

I can't do the following with the current version (which I tend to like to do):

```
// chain the methods one after another
generator
    .on('done', () => {...})
    .on('error', () => {...})
    .start();

// Instead I need to do this currently:
generator.on('done', () => {...});
generator.on('error', () => {...});
generator.start();

```
I know it may seem trivial, but it saves some code by having the event "methods" return **this** (the generator instance), rather than not return anything, so it can be chained. Doesn't impact backwards compatibility.
