### ISSUE TITLE
External sites are crawled

### ISSUE THREAD

**Issue by muster-mark** [hazemhagrass/advanced-sitemap-generator#3]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Links to external URLs are crawled

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const SitemapGenerator = require('advanced-sitemap-generator');

const filePath = 'sitemap.xml';

// create generator
const generator = SitemapGenerator('https://www.markfisher.photo', {
    stripQuerystring: false,
    ignoreHreflang: true,
    lastMod: true,
    filepath: filePath

});

// register event listeners
generator.on('add', url => {
    console.log(`Added page to sitemap: ${url}`);
});

generator.on('done', () => {
    console.log(`Finished building sitemap, and wrote to ${filePath}`);
});

generator.on('error', (error) => {
    console.log(error);
    process.exit();
});

// start the crawler
generator.start();
```

First the homepage is added, then instagram is crawled (though blocked, and returns 403)

**What is the expected behavior?**
Only the domain specified should be crawled

**Comment by hazemhagrass** [comment]
You can use the following options to disable the crawling of any external domain:
    allowInitialDomainChange: false, filterByDomain: true

allowInitialDomainChange: Controls whether the crawler is allowed to change the host setting if the first response is a redirect to another domain.
filterByDomain: Controls whether the crawler fetches only URL's where the hostname matches host. Unless you want to be crawling the entire internet, I would recommend leaving this on!
